name: talenta_app
version: 1.1.7+3
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  carousel_slider: 4.2.1
  hexcolor: 3.0.1
  google_fonts: 6.1.0
  intl: any
  flutter_map_location_marker: ^8.0.8
  month_year_picker: ^0.3.0+1
  camera: 0.10.5+9
  file_picker: 6.2.0
  shared_preferences: ^2.2.2
  gap: 3.0.1
  geolocator: ^11.0.0
  lottie: ^3.1.0
  image_picker: 1.0.7
  local_auth: ^2.2.0
  internet_connection_checker: ^1.0.0+1
  another_stepper: ^1.2.2
  table_calendar: ^3.0.9
  month_picker_dialog: ^2.11.2
  dio: ^5.4.2+1
  permission_handler: 11.3.1
  iconsax: ^0.0.8
  geocoding: ^3.0.0
  flutter_image_compress: 2.2.0
  custom_navigation_bar: ^0.8.2
  package_info_plus: 8.0.0
  shimmer: ^3.0.0
  path_provider: ^2.1.3
  uuid: 4.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: assets/images/img_app_logo.png
  min_sdk_android: 21
  android: true
  ios: true

flutter:
  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/
  uses-material-design: true
